## Math in python 
---

### Imports

In [3]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

### NumPy arrays

In [ ]:
# 1D and 2D arrays, check shape & dtype
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("a:", a, "shape:", a.shape, "dtype:", a.dtype)
print("b:", b, "shape:", b.shape, "dtype:", b.dtype)

a: [1 2 3] shape: (3,) dtype: int64
b: [[1 2 3]
 [4 5 6]] shape: (2, 3) dtype: int64


In [8]:
# Cell 2: Vectorized arithmetic & dot product
c = a + 10           # add scalar
d = a * 2            # multiply by scalar
e = np.array([1, 1, 1])
f = a + e           # add vector

dot = np.dot(a, [4,5,6])  # dot product
print("c:", c)
print("d:", d)
print("dot(a,[4,5,6]):", dot)
print("f:", f)


c: [11 12 13]
d: [2 4 6]
dot(a,[4,5,6]): 32
f: [2 3 4]


sum_bc:
 [[2 4 6]
 [5 7 9]]
